# Lab 02 - numpy

Name: Kartikeya Sharma  
Class: CSCI 349 - Intro to Data Mining  
Semester: 2021SP  
Instructor: Brian King  

In [88]:
import sys
import numpy as np
print(sys.version)
print(np.__version__)

3.8.8 (default, Feb 24 2021, 13:46:16) 
[Clang 10.0.0 ]
1.19.2


In [89]:
def _get_formatted_str_to_sig_figs(input_value: float, num_sig_figs: int):
    '''
    This private, local utility function returns a string 
    representation for later use with the print function, so that 
    the print function displays the inputted value input_value to 
    the number of significant figures specified by num_sig_figs.
    
    Utility has been borrowed (with slight modification) 
    from the following source:
    https://stackoverflow.com/questions/42052605/round-python-float-to-4-significant-digits-on-output-in-different-numeric-range.
    All documentation has been done by myself, Kartikeya Sharma.
    
    Parameters:
        input_value (float): value to be later printed using the
                             formatted string generated by
                             this function
        num_sig_figs (int):  number of significant figures to
                             later print out using the formatted
                             string generated by this function
                             
    Returns:
        str: formatted string that can later be used with
        the print function to print out input_value to
        the number of significant figures specified by 
        num_sig_figs.
        
    '''
    from decimal import Decimal,ROUND_HALF_EVEN,Context
    ctx = Context(prec=num_sig_figs, rounding=ROUND_HALF_EVEN)
    return str(ctx.create_decimal(input_value))

#### 1. [P] Create a 52500 x 75 matrix of zeros, stored as X. Then, print out the shape of the matrix, the base data type, the individual item size in the array, and the total size of the array in bytes (as an integer). Also, print out the total size in megabytes with 3 significant digits.

In [90]:
# parameters
X_num_rows = 52500
X_num_cols = 75
num_sig_figs = 3

X = np.zeros((X_num_rows, X_num_cols))

print("Statistics of ndarray X:")
print()
print("shape of the matrix: " + str(X.shape))
print("base data type: " + str(X.dtype))
print("individual item size (bytes): " + str(X.itemsize) + " bytes")
print("total size (in bytes) " + str(X.nbytes) + " bytes")

bytes_to_megabytes_factor = 1 / 10**6 # multiply this by # bytes to convert
                                      # bytes to MB; 1/2^20 was used
                                      # traditionally, but what was formerly 
                                      # called megabyte is now called mebibyte
                                      # <sup>1 2</sup> <-- sources (see bottom)
total_size_in_megabytes = X.nbytes * bytes_to_megabytes_factor

print("total size (in megabytes): " + \
      str(get_to_sig_figs(total_size_in_megabytes, 
                          num_sig_figs)) + " MB" \
     )

# Sources:
#     1. https://www.wolframalpha.com/input/?i=bytes+to+megabytes
#     2. https://stackoverflow.com/questions/2365100/converting-bytes-to-megabytes

Statistics of ndarray X:

shape of the matrix: (52500, 75)
base data type: float64
individual item size (bytes): 8 bytes
total size (in bytes) 31500000 bytes
total size (in megabytes): 31.5 MB


#### 2. [P] Resize X to have the same number of elements, but with 100 columns. Show the shape. Show the number of bytes (which should be the same as the previous answer)

In [91]:
# parameters
num_cols = 100
num_rows = (int) (X.size / num_cols)

X.resize(num_rows, num_cols)

print("shape of X: " + str(X.shape))
print("total size (in bytes): " + str(X.nbytes) + " bytes")

shape of X: (39375, 100)
total size (in bytes): 31500000 bytes


#### 3. [P] Redo #1, but use a base datatype of 16-bit integers.

In [92]:
# parameters
X_num_rows = 52500
X_num_cols = 75
num_sig_figs = 3

X = np.zeros((X_num_rows, X_num_cols), dtype=np.int16)

print("Statistics of ndarray X:")
print()
print("shape of the matrix: " + str(X.shape))
print("base data type: " + str(X.dtype))
print("individual item size (bytes): " + str(X.itemsize) + " bytes")
print("total size (in bytes) " + str(X.nbytes) + " bytes")

bytes_to_megabytes_factor = 1 / 10**6 # multiply this by # bytes to convert
                                      # bytes to MB; 1/2^20 was used
                                      # traditionally, but what was formerly 
                                      # called megabyte is now called mebibyte
                                      # <sup>1 2</sup> <-- sources (see bottom)
total_size_in_megabytes = X.nbytes * bytes_to_megabytes_factor

print("total size (in megabytes): " + \
      str(get_to_sig_figs(total_size_in_megabytes, num_sig_figs)) + " MB" \
     )

# Sources:
#     1. https://www.wolframalpha.com/input/?i=bytes+to+megabytes
#     2. https://stackoverflow.com/questions/2365100/converting-bytes-to-megabytes

Statistics of ndarray X:

shape of the matrix: (52500, 75)
base data type: int16
individual item size (bytes): 2 bytes
total size (in bytes) 7875000 bytes
total size (in megabytes): 7.88 MB


#### 4. [P] How many dimensions does X have? Answer using the appropriate property of np.ndarray objects.

In [93]:
print("number of dimensions of X: " + str(X.ndim) + " dimensions")

number of dimensions of X: 2 dimensions


#### 5. [P] Enter the following Python list in your cell:

```python str_nums = ['2.14', '-9.300', '42'] ```

#### Convert this to a numpy array named X. What is the base type? Show the contents of X.

#### Then, convert X to an array of single precision floating point numbers. (HINT: use astype). Show X again.

In [94]:
str_nums = ['2.14', '-9.300', '42'] # given in instructions

X = np.array(str_nums)
print("base type of X: " + str(X.dtype) + " (little-endian 6-length Unicode string)")
print(X)
print()
X = X.astype(np.float32, copy=False)
print("X as single precision floating point as base type: \n" + str(X))

base type of X: <U6 (little-endian 6-length Unicode string)
['2.14' '-9.300' '42']

X as single precision floating point as base type: 
[ 2.14 -9.3  42.  ]


#### Let's assume you have two week's worth of quiz scores. Quizzes are out of 10 points, and are given every day. Enter the following in your cell:

#### ```python days = ["Mon","Tue","Wed","Thu","Fri"] ```
#### ```python scores_1 = [9.5, 8.75, 8, 10, 7.75] ```
#### ```python scores_2 = [9, 8, 10, 8.75, 7.25] ```

#### The array scores_1 represents quiz scores from week 1, and scores_2 is week 2. The days array will be used for data selection purposes.

#### 6. [P] Copy the three definitions above for the Python lists days, scores_1, and scores_2. Create a numpy array called scores that has scores_1 as the first row and scores_2 as the second row using np.concatenate. Then, change days into a np.array from the list days. Show the contents of scores and days, and output their shape.

In [95]:
days = ["Mon","Tue","Wed","Thu","Fri"]
scores_1 = [9.5, 8.75, 8, 10, 7.75]
scores_2 = [9, 8, 10, 8.75, 7.25]

scores = np.concatenate(([scores_1], [scores_2]))

days = np.array(days)

print("scores: \n" + str(scores))
print("days: " + str(days))
print()
print("shape of scores: " + str(scores.shape))
print("shape of days: " + str(days.shape))

scores: 
[[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]]
days: ['Mon' 'Tue' 'Wed' 'Thu' 'Fri']

shape of scores: (2, 5)
shape of days: (5,)


#### 7. [P] Repeat the previous problem with the creation of scores from the Python lists scores_1 and scores_2, but now do it with np.vstack. The array should be identical.

#### REMINDER - Do not simply answer questions using functions or methods you know nothing about! If you have not seen vstack before, then look it up!

In [96]:
days = ["Mon","Tue","Wed","Thu","Fri"]
scores_1 = [9.5, 8.75, 8, 10, 7.75]
scores_2 = [9, 8, 10, 8.75, 7.25]

scores = np.vstack((scores_1, scores_2))

days = np.array(days)

print("scores: \n" + str(scores))
print("days: " + str(days))
print()
print("shape of scores: " + str(scores.shape))
print("shape of days: " + str(days.shape))

scores: 
[[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]]
days: ['Mon' 'Tue' 'Wed' 'Thu' 'Fri']

shape of scores: (2, 5)
shape of days: (5,)


#### For the next several questions, you are going to exercise some advanced data selection techniques using the days array to assist with looking up data. For example, if you are asked to reveal the scores from only Friday, then you must write the numpy selection expression to do this. For example, the following shows the scores only from Friday:

```python scores[:, days == "Fri"] ```

#### 8. [P/M] Compare the result of the expression days == "Fri" if the variable days was a Python list as entered above, vs. days being a numpy array. What is the difference in the result? **In general, how does numpy deal with standard comparison operators?**

In [97]:
days = ["Mon","Tue","Wed","Thu","Fri"]
print("days == Fri if days is Python list: " + str(days == "Fri"))

days = np.array(days)
print("days == Fri if days is numpy array: " + str(days == "Fri"))

days == Fri if days is Python list: False
days == Fri if days is numpy array: [False False False False  True]


<br/>

As a Python list, days as a Python list object is compared against the string object "Fri," which are not equivalent to one another. Hence, False is outputted when the result of this comparison is printed. 

On the other hand, in the case where days is a numpy array, the value of the string "Fri" is compared with, for value-equivalency rather than memory address being referenced that is, each string item within the days array. Each item in the output numpy array was a boolean value positionally-corresponding to whether the string value at the corresponding position in days was "Fri" (True) or not (False). The == operator is processed by the Python interpretor as a call to the hidden (private) method \_\_eq\_\_, which are presumably implemented differently in the built-in Python list class and numpy ndarray class.<sup>2</sup> 

Unlike what is the case with using built-in Python operations, NumPy allows developers using the NumPy package to perform operations on arrays without manually writing iterative loops. This reduces the inefficiency/overhead traditionally required in order to perform those operations in Python (iteratively so, i.e. with for loops); within the development community associated with NumPy, this concept is known as vectorization.<sup>1</sup> By default, NumPy interprets standard operators to be operated upon "element-wise."<sup>1</sup> In "element-wise" operations, each value at a particular position in the array before the operation is operated with the positionally corresponding value in the latter array; the result of each such operation is position-correspondingly placed in the array resulting from the operation.<sup>1</sup> Of course, this would require the two arrays being operated with, as well as the resulting array, to be of the same dimensions. 

Sources
1. https://learning.oreilly.com/library/view/python-for-data/9781491957653/ch04.html
2. *The source of this knowledge is from what I learned in CSCI 204 "Data Structures & Algorithms."*

#### 9. [P] Select the scores that fell on Monday. 
#### HINT: For cells that ask for only one output, you can sometimes avoid a print statement. The expression evaluated as the last line of a cell will also be the output of the cell. For example, if I did not use the print function, here's what the answer would look like:

   #### &emsp;&ensp; 9) Select the scores that fell on Monday
   #### &emsp;&ensp; ``` scores[:,days=="Mon"] ```
   #### &emsp;&ensp; array(\[\[9.5\],
   #### &emsp;&ensp; &emsp;&emsp;&emsp;&nbsp;\[9. \]\])
   
    

In [98]:
monday_cond = days=="Mon" # condition for which positions along the 
                          # 0 axis in scores contains scores that fell on Monday.

scores[:,monday_cond]

array([[9.5],
       [9. ]])

#### 10. [P] Select all of the scores that are NOT on Monday (Hint – look up the ~ operator)

In [99]:
scores[:,~monday_cond]

array([[ 8.75,  8.  , 10.  ,  7.75],
       [ 8.  , 10.  ,  8.75,  7.25]])

#### 11. [P] Select the scores that were on Tuesday or Thursday

In [100]:
scores[:,((days=="Tue") | (days=="Thu"))]

array([[ 8.75, 10.  ],
       [ 8.  ,  8.75]])

#### 12. [P] Show the minimum and maximum scores for the entire array of scores

In [101]:
print("maximum score in ndarray scores: " + str(scores.max()))
print("minimum score in ndarray scores: " + str(scores.min()))

maximum score in ndarray scores: 10.0
minimum score in ndarray scores: 7.25


#### 13. [P] Show the minimum scores for each week as a new array. The result should have the same dimensions (hint – use the keepdims parameter of np.min). Your result should be something like:

   #### &emsp;&ensp; array(\[\[7.75\],
   #### &emsp;&ensp; &emsp;&emsp;&emsp;&nbsp;\[7.25\]\])

In [102]:
scores.min(axis=1, keepdims=True)

array([[7.75],
       [7.25]])

#### 14. [P] Report the day that the maximum score occurred each week. (HINT: use argmax and use that result to index days.)

In [109]:
def argmax_keepdims(ndarr: np.ndarray, axis: int):
    """
    This function returns the index values of the maximum values 
    along a specified axis, while preserving the dimensions of the
    original (inputted) ndarray object arr.

    The axis which is reduced is left in the result as dimension 
    with size one. The result will broadcast correctly 
    against the input array.

    Original numpy.argmax() implementation does not currently 
    support the keepdims parameter.
    See https://github.com/numpy/numpy/issues/8710 
    for further information.
    
        Parameters:
                arr (ndarray): ndarray object to
                               find the maximum value
                               along the axis specified on
                axis (int): axis to perform the maximum value
                            search on
        Returns:
                np.ndarray: ndarray object containing the dimensions
                            along the axis for each non-axis 
                            dimension(s) while preserving
                            dimensionality of the inputted
                            np.ndarray object ndarr
    """
    output_shape = list(ndarr.shape)
    output_shape[axis] = 1
    return np.argmax(ndarr, axis=axis).reshape(output_shape)

days[argmax_keepdims(scores, 1)] # keep dimensions
                                 # display weekday of max score 
                                 # for each week in each row

array([['Thu'],
       ['Wed']], dtype='<U3')

#### 15. [P] Report the mean of the scores of each week

In [ ]:
scores.mean(axis=1, keepdims=True)

#### 16. [P] Suppose the lowest score was dropped from each week. Report the mean of each week, but without the minimum score for that week.

In [ ]:
scores_wo_lowest_score_in_wk = np.delete(scores,scores.argmin(axis=1),axis=1)
scores_wo_lowest_score_in_wk.mean(axis=1, keepdims=True)

#### 17. [P] Convert the scores to fall on a scale from 0-100 instead of 0-10. Show the result.

In [ ]:
# assuming scale starts at 0 and includes integers
# creating section for parameters to avoid magic numbers
curr_max_scale_val = 10
target_max_scale_val = 100
change_max_scale_factor = target_max_scale_val / curr_max_scale_val

scores *= change_max_scale_factor
print("scores:\n" + str(scores))

#### Copy and paste this code into a cell:

In [ ]:
np.random.seed(1234)
X = np.random.randint(1,100,50).reshape((10,5))
X

#### You may use standard selection techniques with integers and slicing for the following exercises. Be sure to show your results of each. (Most of these are one-line statements, and thus you won't need a print function.) For each of these, you should only show the result of the selection. Do NOT reassign X.

#### 18. [P] Select the first row of X

In [ ]:
num_row_to_select = 1 # 1 for 1st, 2 for 2nd, and so on
X[[num_row_to_select-1],:]   # keep dimensions

#### 19. [P] Select the last column of X

In [ ]:
X[:,-1:]

#### 20. [P] Select the first AND last column of X

In [ ]:
column_index_values = [0, -1]

X[:,column_index_values]

#### 21. [P] Select every other row of X

In [ ]:
every_nth_row = 2 # every nth row (after first row)

X[::every_nth_row,:]

#### 22. [P] Show the transpose of X, but don't change X itself

In [ ]:
X.T

#### 23. [P] Select the first column of X and set the result to Y. 

In [ ]:
# parameters to avoid magic numbers
column_num = 1 # 1 is first, 2 is second, etc.
column_index = column_num - 1

Y = X[:,[column_index]]
Y

#### 24. [P] Increment the first value of Y, then show the corresponding value of X. Did both values in X and Y change? THIS IS AN IMPORTANT OBSERVATION WHEN DEALING WITH SELECTING DATA!

In [ ]:
# parameters
row_index = 0
col_index = 0

Y[row_index][col_index] += 1
print("X: \n" + str(X))
print()
print("Y: \n" + str(Y))

Yes, both X and Y changed because Y is a 'sliced' view of the array in X.

#### 24. [P] Repeat exercise 23, but ensure that Y is assigned a copy of the selected data. Increment the first value of Y again and ensure that the corresponding value of X did not change.

In [ ]:
Y = X[:,:1].copy()

Y[0][0] += 1
print("X: \n" + str(X))
print()
print("Y: \n" + str(Y))

The first value of Y was successfully incremented and the corresponding value of X was not. This is due to the fact that a deep copy was made of the sliced view of X, which was then assigned to Y. Afterwards, the first value in Y was incremented, incrementing the first value in Y and not of the corresponding value in X.

#### 26. [P] Create an array that contains the sequence of numbers 0, 0.1, 0.2, ... 9.8, 9.9 using arange, as a 10x10 matrix, stored as X.

In [ ]:
X = np.arange(0,10,0.1).reshape(10,10)
print(X)

#### 27. [P] Set the RNG seed to 1234. Then create an array X of 100 uniformly distributed numbers, with all values between 1.0 and 10.0. Then, show the mean, the median, the minimum and maximum values of X.

In [ ]:
rng_obj = np.random.default_rng(1234)
X = rng_obj.uniform(low=1.0, high=10.0, size=100)
print("mean of X: " + str(np.mean(X)))
print("median of X: " + str(np.median(X)))
print("minimum value of X: " + str(np.min(X)))
print("maximum value of X: " + str(np.max(X)))

#### 28. [M] Define what is meant by a normal distribution. What are the parameters of a normal distribution?

In statistics, a *distribution* is a relative model of how many times each value an output variable will hold in some number of trials.<sup>1</sup> A *normal* distribution is, generally speaking, a statistical distribution characterized by a symmetric bell curve (one peak/unimodal) that asymptotically approaches 0 from either direction descending from the peak (theoretically with an infinite number of trials for a perfectly normal distribution), where the mean, median, and mode are equal.<sup>2</sup> About 68 percent of the trials have a value within one standard deviation of the mean value, about 95 percent of the trials have a value within two standard deviations of the mean value, and about 99.7 percent of the trials have a value within three standard deviations of the mean value.<sup>2</sup> Strictly speaking, a normal distribution having an output variable $x$, mean $\mu$, and standard deviation $\sigma$ is characterized by a "probability density function $P(x) = \frac{1}{\sigma \sqrt[]{2\pi}} e^{-(x-\mu)^2/(2\sigma^2)}$ ," where the domain of $x$ ranges from -$\infty$ to $\infty$.<sup>3</sup> 

Specifically, the parameters for a *perfectly* normal distribution are the mean $\mu$ and the standard deviation $\sigma$; an approximate normal distribution would require additional specification of their unique probability density function (assuming the output variable is continuous) or their probability mass function (if the output variable is instead discrete but a plot of the number of outcome of values across trials resembles a normal distribution).

Normal distributions have been useful for describing naturally occurring phenomenon with "tiny, random disturbances."<sup>4</sup>

Sources: 
1. https://mathworld.wolfram.com/StatisticalDistribution.html
2. https://www.khanacademy.org/math/statistics-probability/modeling-distributions-of-data/normal-distributions-library/a/normal-distributions-review
3. https://mathworld.wolfram.com/NormalDistribution.html
4. https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.normal.html#numpy.random.Generator.normal

#### 29. [M] In simple terms, using a normal distribution, what does the Law of Large Numbers tell us?

The Law of Large Numbers says that as more (generally many) independent<sup>*</sup> samples are taken, the average of the samples will approach/converge to (with large likelihood) that of the true, "underlying distribution." <sup>1 2 3</sup> The 'underlying distribution' can be thought of as the distribution of the whole dataset being sampled, estimated, analyzed, etc. Moreover, it says that the density histogram of those samples will approach that of the true, "underlying distribution," which, in this case, is a normal distribution because the prompt specifies that the answer should use a normal distribution. <sup>1</sup>

<font size="2"> *meaning that the result of one sample is not affected by factors outside of the sample like the result of other samples, the order in which the sample is taken relative to the other samples taken, or changes to the probability density function mid-experiment <sup>3</sup></font>

Sources:
1. https://ocw.mit.edu/courses/mathematics/18-05-introduction-to-probability-and-statistics-spring-2014/readings/MIT18_05S14_Reading6b.pdf
2. http://www2.stat.duke.edu/~vp58/sta111/lecture8.pdf
3. https://www.math.arizona.edu/~rsims/ma464/chap8_11_22.pdf

#### 30. [P] Write a function called ```test_normal_dist```. The purpose of this function is to evaluate the law of large numbers. It should have four parameters: 

#### ```mu``` = mean of distribution 
#### ```sd``` = standard deviation
#### ```vec_length``` = length of the vector to generate randomly from a normal distribution, with mu and sd as parameters
#### ```num_trials``` = number of times to repeat the experiment

#### The function should behave as follows. First, initialize the seed value to 1234, before your loop. Then, loop for ```num_trials```, generating ```vec_length``` numbers from a normal distribution. Compute the mean of that vector, then compute its deviation (absolute value of the observed mean - expected mean). This should be repeated for all trials, and then return the *average deviation* over all trials.

In [113]:
def test_normal_dist(mu: float, 
                     sd: float, 
                     vec_length: int, 
                     num_trials: int):
    '''
    This function generates num_trials trials with the sample size
    in each trial of vec_length given a mu and standard deviation 
    of the underlying normal distribution being sampled; then, the
    average deviation over all of the trials is returned.
    
    Parameters:
            mu (float): average value of the underlying 
                        distribution that each trial in the 
                        experiment is sampling
            std (float): standard deviation of the underlying
                         distribution that each trial in the
                         experiment is sampling
            vec_length (int): sample size of each trial
            num_trials (int): number of trials to perform
    
    Returns:
            float: average deviation over all of the trials in
                   the given experiment, the underlying
                   distribution of which had a normal
                   distribution with a given average, mu, and
                   given standard deviation, sd
                            
    '''
    rand_num_gen = \
    np.random.default_rng(1234) # setting random number generator 
                                # seed to 1234
    samp_vecs = np.zeros(
        (num_trials, 
         vec_length)) # intializing sample vectors with 0
    
    for i in range(num_trials): # problem specifies loop, 
                                # so did not make 2d arr with 
                                 # normal method
        samp_vecs[i] = \
        rand_num_gen.normal(mu, 
                            sd, 
                            vec_length) # generating rand vectors
    
    samp_vec_mean = np.mean(samp_vecs, 
                            axis=1, 
                            keepdims=True) # compute vector mean
    samp_vec_deviation = \
    np.abs(samp_vec_mean - mu) # calculate vector deviation
    
    return np.mean(samp_vec_deviation) # return average deviation 
                                       # for experiment



#### 31. [P] Use test_normal_dist to obtain the deviation for vector lengths of 10, 100, 1000, 10000, and 100000. Use a fixed number of trials of 100 for each experiment. Report the results as a numpy array with two dimensions. the first being the vector length, and the second being the average deviation resulting from your test_normal_dist function. Your resulting array should look like:

####   ```[[    10.        0.4772]```
####   &ensp;&nbsp;```[   100.        0.1619]```
####   &ensp;&nbsp;```[  1000.        0.0446]```
####   &ensp;&nbsp;```[ 10000.        0.0159]```
####   &ensp;&nbsp;```[100000.        0.0049]```


#### In other words, your results should confirm the Law of Large Numbers.

In [118]:
mu = 0
sd = 1
num_trials = 100 # constant specified in problem description
vec_lengths = np.power(10, 
                       (np.arange(1,6))).T # array of vector
                                           # lengths 10^1
                                           # through 10^5
vectorized_test_normal_dist = \
np.vectorize(test_normal_dist,
             excluded=['mu',
                       'sd',
                       'num_trials']) # vectorized function of 
                                      # test_normal_dist
                                      # exclude constant parameters
                                      # from being vectorized
                                      # the only parameter 
                                      # requiring vectorization
                                      # is the list of vector
                                      # lengths
results = vectorized_test_normal_dist(mu=mu,
                                      sd=sd,
                                      vec_length=vec_lengths,
                                      num_trials=num_trials) 
vec_lengths_and_results = \
np.vstack((vec_lengths, results)).T # stack vector lengths
                                    # and standard deviation
                                    # results, then store
                                    # transpose; transposed
                                    # matrix pairs the columns
                                    # such that each vector
                                    # length in the first row
                                    # and each resulting standard
                                    # deviation in the second row 
                                    # of the original matrix are
                                    # in the same row of the
                                    # transposed matrix

np.set_printoptions(precision=4, 
                    suppress=True) # specify how many decimals 
                                   # to print
print(vec_lengths_and_results)

[[    10.          0.2436]
 [   100.          0.0784]
 [  1000.          0.0249]
 [ 10000.          0.0076]
 [100000.          0.0024]]
